// <auto-generated />
using System;
using Lumina_Hospital.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lumina_Hospital.Migrations
{
    [DbContext(typeof(LuminaHospitalDbContex))]
    [Migration("20231219104759_AddVideoAndVideoTitleTableWithRelation")]
    partial class AddVideoAndVideoTitleTableWithRelation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Lumina_Hospital.Entities.VideoSection.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 12, 19, 14, 47, 59, 185, DateTimeKind.Local).AddTicks(511),
                            IsDelete = false,
                            VideoPath = "~/assets/images/video/med.mp4"
                        });
                });

            modelBuilder.Entity("Lumina_Hospital.Entities.VideoSection.VideoTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("VideoTitles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 12, 19, 14, 47, 59, 185, DateTimeKind.Local).AddTicks(743),
                            IsDelete = false,
                            Title = "Your Trusted Destination",
                            VideoId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2023, 12, 19, 14, 47, 59, 185, DateTimeKind.Local).AddTicks(745),
                            IsDelete = false,
                            Title = "Here for You and Your Health",
                            VideoId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2023, 12, 19, 14, 47, 59, 185, DateTimeKind.Local).AddTicks(746),
                            IsDelete = false,
                            Title = "Good Living, Good Health",
                            VideoId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2023, 12, 19, 14, 47, 59, 185, DateTimeKind.Local).AddTicks(748),
                            IsDelete = false,
                            Title = "We Care, Your Smile Matters",
                            VideoId = 1
                        });
                });

            modelBuilder.Entity("Lumina_Hospital.Entities.VideoSection.VideoTitle", b =>
                {
                    b.HasOne("Lumina_Hospital.Entities.VideoSection.Video", "Video")
                        .WithMany("VideoTitles")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Lumina_Hospital.Entities.VideoSection.Video", b =>
                {
                    b.Navigation("VideoTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
